# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = bioskop.o Logic.o List.o
LINKOBJ  = bioskop.o Logic.o List.o
LIBS     = -L"D:/Software/DevC/Dev-Cpp/MinGW64/lib" -L"D:/Software/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Software/DevC/Dev-Cpp/MinGW64/include" -I"D:/Software/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Software/DevC/Dev-Cpp/MinGW64/include" -I"D:/Software/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Software/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TubesSDA.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

bioskop.o: bioskop.cpp
	$(CPP) -c bioskop.cpp -o bioskop.o $(CXXFLAGS)

Logic.o: Logic.cpp
	$(CPP) -c Logic.cpp -o Logic.o $(CXXFLAGS)

List.o: List.cpp
	$(CPP) -c List.cpp -o List.o $(CXXFLAGS)
